_wandb:
    value:
        cli_version: 0.26.1
        e:
            j56j9sk24qpurjk85gpem5ephz50dq06:
                codePath: /workspace/EO-SAR_Change_Detection/train.ipynb
                codePathLocal: train.ipynb
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "26843545600"
                        used: "1012498432"
                email: karanjayakumar22@gmail.com
                executable: /workspace/EO-SAR_Change_Detection/env/bin/python
                git:
                    commit: 9b0dce1fead7dadba21856bec353e51d02e8c394
                    remote: https://github.com/Karan-00-11/EO-SAR_Change_Detection.git
                gpu: NVIDIA RTX A5000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-dbb3bdaf-291d-7055-ee92-0334e65268a7
                host: 069abb1c8c1f
                memory:
                    total: "540647591936"
                os: Linux-5.15.0-102-generic-x86_64-with-glibc2.35
                program: /workspace/EO-SAR_Change_Detection/train.ipynb
                python: CPython 3.11.10
                root: /workspace/EO-SAR_Change_Detection
                startedAt: "2026-05-10T21:22:53.493623Z"
                writerId: j56j9sk24qpurjk85gpem5ephz50dq06
        m: []
        mask/class_labels:
            examples_wandb_delimeter_gt:
                key: examples_wandb_delimeter_gt
                type: mask/class_labels
                value:
                    "0": no-change
                    "1": change
            examples_wandb_delimeter_pred:
                key: examples_wandb_delimeter_pred
                type: mask/class_labels
                value:
                    "0": no-change
                    "1": change
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.10
            "5": 0.26.1
            "8":
                - 1
            "12": 0.26.1
            "13": linux-x86_64
augmentations:
    value:
        color_jitter:
            brightness: 0.15
            contrast: 0.15
            hue: 0.02
            probability: 0.5
            saturation: 0.1
        gaussian_blur:
            probability: 0.2
        horizontal_flip:
            probability: 0.5
        intensity_scale:
            probability: 0.5
        vertical_flip:
            probability: 0.5
data:
    value:
        data_root: Data
        image_size: 1024
        index_path: Data/index/patch_metadata.npz
        patch_size: 256
        stride: 128
        test:
            post_event: Data/test/post-event
            pre_event: Data/test/pre-event
            target: Data/test/target
        train:
            post_event: Data/train/post-event
            pre_event: Data/train/pre-event
            target: Data/train/target
        val:
            post_event: Data/val/post-event
            pre_event: Data/val/pre-event
            target: Data/val/target
dataset_thresholds:
    value:
        change_thr: 0.001
        hard_neg_thr: 0.1
        informative_thr: 0.084
        valid_thr: 0.25
metrics:
    value:
        image_log_every: 3500
        log_f1: true
        log_images: true
        log_iou: true
        log_precision: true
        log_recall: true
        log_steps: 500
project:
    value:
        name: EO-SAR Change-Detection
        run_name: cmcdnet-run-001
sampler:
    value:
        ratios:
            hard_negative: 0.25
            informative: 0.625
            trivial: 0.125
training:
    value:
        batch_size: 16
        epochs: 10
        learning_rate: 0.0001
        loss: bce_dice
        optimizer: adam
        seed: 42
        weight_decay: 0.0001
